# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: '<your-service-connection-number'
  dockerfilePath: '$(Build.SourcesDirectory)/taskapp/taskapp/Dockerfile'
  containerRegistry: 'sdefontaine123'
  imageRepository: 'azure-docker-demo'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: 'buildAndPush'
        repository: '$(containerRegistry)/$(imageRepository)'
        dockerfile: '$(Build.SourcesDirectory)/taskapp/taskapp/Dockerfile'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        buildContext: '.'
        tags: |
          $(tag)